name: app_jam_uygulama
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bottom_navigation_bar: ^1.0.1
  chewie: ^1.4.0
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  shared_preferences: ^2.1.0
  syncfusion_flutter_calendar: ^21.1.38
  syncfusion_localizations: ^21.1.38
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
